name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install bun
        uses: oven-sh/setup-bun@v2
      
        

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      
      - name: Install playwright
        run: bunx playwright install

      - name: Install dependencies
        run: bun install

      - name: Run e2e tests
        run: bun run test:playwright

      - name: Build Next.js
        run: bun run build